### ISSUE TITLE
e-mails not working

### ISSUE THREAD

**Issue by frequency1** [raafael911/redmine_reminder#10]
Trace result

** Invoke /netflow/var/www/html/redmine/Rakefile (first_time, not_needed)
** Invoke redmine:reminder:send_notification (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:reminder:send_notification
rake aborted!
ActiveRecord::RecordNotFound: Couldn't find all Issues with 'id': (all, {:include=>[:assigned_to, :status, :tracker, :project, :priority], :conditions=>"projects.id = 8"}) [WHERE (issue_statuses.is_closed = 0)] (found 0 results, but was looking for 2)
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:336:in `raise_record_not_found_exception!'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:479:in `find_some'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:438:in `find_with_ids'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:71:in `find'
/netflow/var/www/html/redmine/plugins/redmine_reminder/lib/tasks/mailer.rake:10:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:reminder:send_notification

**Comment by raafael911** [comment]
A few more details would help me. Like your Redmine environment, version, etc.
